node {
    stage('SCM') {
        checkout scm
    }

    stage('verify') {
        sh 'ls -la'
    }

    stage('SonarQube Analysis') {
        def scannerHome = tool 'SonarScanner';
        withSonarQubeEnv() {
            sh "${scannerHome}/bin/sonar-scanner"
        }
    }
}